#!/usr/bin/env zsh

type 'fzf' &>/dev/null || { echo 'fzf is not installed' && exit 1 }
type 'bat' &>/dev/null || { echo 'bat is not installed' && exit 1 }

local file
local query=''

[[ -z $@ ]] || { query="$@" }

local preview=$(cat <<'EOF'
bat \
	--style=numbers \
	--color=always \
	--terminal-width="$(( $(tput cols) / 4 * 3 ))" \
	{}
EOF
)

local width="$(tput cols)"
local preview_width="$(( $width / 4 * 3 ))"
local preview_width_folded="$(( $width / 5 ))"

local preview_window="right:${preview_width}:border-vertical"
local bind_fold="change-preview-window(${preview_width_folded}|${preview_width})"

fzf \
	--cycle \
	--query="$query" \
	--preview="$preview" \
	--preview-window="$preview_window" \
	--bind="ctrl-\\:${bind_fold}" |
read -r file

[[ -z $file ]] || { bat "$file" }
