#!/usr/bin/env zsh

type 'fzf' &>/dev/null || { echo 'fzf is not installed' && exit 1 }
type 'delta' &>/dev/null || { echo 'delta is not installed' && exit 1 }

local query=''

[[ -z $@ ]] || { query="$@" }

local preview=$(cat <<'EOF'
git diff --staged {} |
delta \
  --width=$(( $(tput cols) / 10 * 7 ))
EOF
)

git diff \
  --relative \
  --staged \
  --name-only |
fzf \
  --cycle \
  --query "$query" \
  --preview-window '70%' \
  --preview "$preview" > /dev/null
