#!/usr/bin/env zsh

type 'fzf' &>/dev/null || { echo 'fzf is not installed' && exit 1 }

local branch
local query=''

[[ -z $@ ]] || { query="$@" }

local width="$(tput cols)"
local preview_width="$(( $width / 4 * 3 ))"
local preview_width_folded="$(( $width / 5 ))"

local preview_window="right:${preview_width}:border-vertical"
local bind_fold="change-preview-window(${preview_width_folded}|${preview_width})"

git branch -a |
sed -E 's/^(\*| ) //' |
sed -E 's/^\(HEAD detached at (.+)\)$/\1/' |
awk '{print $NF}' |
fzf \
	--cycle \
	--query="$query" \
	--preview='git logs {}' \
	--preview-window="$preview_window" \
	--bind="ctrl-\\:${bind_fold}" |
sed -E 's/^(remotes\/)?(origin\/)?//' |
xargs git switch
