#!/usr/bin/env zsh

type 'fzf' &>/dev/null || { echo 'fzf is not installed' && exit 1 }
type 'micro' &>/dev/null || { echo 'bat is not installed' && exit 1 }

local file
local query=''

[[ -z $@ ]] || { query="$@" }

local preview=$(cat <<'EOF'
bat \
  --style=numbers \
  --color=always \
  --line-range :200 \
  {}
EOF
)

fzf \
  --cycle \
  --query "$query" \
  --preview "$preview" |
read -r file

[[ -z $file ]] || { micro "$file" }
